# Generated by Django 4.2 on 2025-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Менеджер', 'Менеджер'), ('Преподаватель', 'Преподаватель'), ('Ученик', 'Ученик')], default='Ученик', max_length=20),
        ),
    ]
