# Generated by Django 4.2 on 2025-09-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='left_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ухода'),
        ),
    ]
