# Generated by Django 4.2 on 2025-09-19 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Отсутствовал'), ('1', 'Присутствовал'), ('online', 'Онлайн')], max_length=10)),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемости',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер кабинета')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveIntegerField(verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('rent', 'Аренда'), ('marketing', 'Маркетинг'), ('office', 'Хозяйственные'), ('other', 'Другое')], max_length=10, verbose_name='Категория')),
                ('description', models.CharField(max_length=255, verbose_name='Статья расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('yearly', 'Ежегодный')], max_length=10, verbose_name='Тип отчёта')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирован')),
            ],
            options={
                'verbose_name': 'Финансовый отчёт',
                'verbose_name_plural': 'Финансовые отчёты',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('age_group', models.CharField(max_length=50, verbose_name='Возрастная группа')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн')], max_length=10, verbose_name='Формат')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Продолжительность (месяцы)')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('planned_start', models.DateField(verbose_name='Планируемое начало')),
                ('lessons_per_month', models.PositiveIntegerField(verbose_name='Занятий в месяц')),
                ('lesson_duration', models.PositiveIntegerField(verbose_name='Продолжительность занятия (часы)')),
                ('lessons_per_week', models.PositiveIntegerField(verbose_name='Занятий в неделю')),
                ('schedule_days', models.CharField(max_length=100, verbose_name='Дни занятий')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_links', models.URLField(default=list)),
                ('files', models.URLField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('green', 'Правильно'), ('orange', 'Отправлено'), ('red', 'Отказано'), ('black', 'Не сделано')], default='submitted', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('online', 'Онлайн')], max_length=10, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('is_full_payment', models.BooleanField(default=True, verbose_name='Полная оплата')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('partial', 'Частично оплачено'), ('paid', 'Оплачено')], default='pending', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('course', models.CharField(max_length=255, verbose_name='Курс')),
                ('status', models.CharField(choices=[('new', 'Новые'), ('in_progress', 'В работе'), ('registered', 'Записан'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('next_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего контакта')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('lesson_links', models.URLField(blank=True, verbose_name='Ссылки урока')),
                ('homework_links', models.URLField(blank=True, verbose_name='Ссылки ДЗ')),
                ('lesson_recording', models.FileField(blank=True, null=True, upload_to='lesson_recordings/', verbose_name='Запись урока')),
                ('homework_files', models.FileField(blank=True, null=True, upload_to='homework_files/', verbose_name='Файлы ДЗ')),
                ('homework_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('homework_description', models.TextField(blank=True, verbose_name='Описание задания')),
                ('homework_requirements', models.TextField(blank=True, verbose_name='Требования к заданию')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField(verbose_name='Номер месяца')),
                ('title', models.CharField(max_length=255, verbose_name='Название месяца')),
                ('description', models.TextField(verbose_name='Описание месяца')),
            ],
            options={
                'verbose_name': 'Месяц курса',
                'verbose_name_plural': 'Месяцы курсов',
                'ordering': ['month_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('online', 'Онлайн')], max_length=10, verbose_name='Тип оплаты')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Имя получателя')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('message_text', models.TextField(verbose_name='Текст обращения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к оплате')),
                ('extra_message', models.TextField(blank=True, null=True, verbose_name='Дополнительное обращение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Уведомление о платежах',
                'verbose_name_plural': 'Уведомления о платежах',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Расписание занятий',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('fixed', 'Фиксированная ставка'), ('hourly', 'Почасовая ставка')], default='fixed', max_length=10, verbose_name='Тип оплаты')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оплаты')),
                ('payment_period', models.CharField(blank=True, choices=[('month', 'В месяц'), ('per_lesson', 'За занятие')], max_length=10, verbose_name='Период оплаты')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_count', models.PositiveIntegerField(verbose_name='Занятий')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выплата')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплачено')),
                ('date', models.DateField(verbose_name='Дата расчета')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Выплата преподавателю',
                'verbose_name_plural': 'Выплаты преподавателям',
                'ordering': ['-date'],
            },
        ),
    ]
