# Generated by Django 4.2 on 2025-09-21 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='files',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файлы с домашним заданием'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='project_links',
            field=models.URLField(verbose_name='Ссылки на проект'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('green', 'Правильно'), ('orange', 'Отправлено'), ('red', 'Отказано'), ('black', 'Не сделано')], default='submitted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
    ]
