# Generated by Django 4.2 on 2025-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_homeworksubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, default='Unknown', max_length=155, null=True, verbose_name='ФИО'),
        ),
    ]
