# Generated by Django 4.2 on 2025-09-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0004_student_full_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='months',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='course',
        ),
        migrations.AddField(
            model_name='invoice',
            name='months',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administration.months', verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='months',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='administration.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='files',
            field=models.JSONField(blank=True, default=list, verbose_name='Файлы с домашним заданием'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='administration.lesson'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='project_links',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки на проект'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('green', 'Правильно'), ('orange', 'Отправлено'), ('red', 'Отказано'), ('black', 'Не сделано')], default='orange', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterUniqueTogether(
            name='months',
            unique_together={('group', 'month_number')},
        ),
        migrations.RemoveField(
            model_name='months',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
