# Generated by Django 4.2 on 2025-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_months_unique_together_remove_invoice_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_recording',
            field=models.URLField(blank=True, null=True, verbose_name='Запись урока'),
        ),
    ]
