# Generated by Django 4.2 on 2025-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_lesson_lesson_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Файлы с домашним заданием'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='project_links',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Ссылки на проект'),
        ),
    ]
