# Generated by Django 4.2 on 2025-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_homeworksubmission_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('green', 'Правильно'), ('orange', 'Отправлено'), ('red', 'Отказано'), ('black', 'Не сделано')], default='black', max_length=20, verbose_name='Статус'),
        ),
    ]
