# Generated by Django 4.2 on 2025-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_homeworksubmission_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.CharField(max_length=255, verbose_name='Сумма скидки(сом)')),
                ('homework_points', models.CharField(max_length=255, verbose_name='Баллы за ДЗ')),
                ('min_attendance', models.CharField(max_length=255, verbose_name='Минимальное кол-во посещений')),
            ],
            options={
                'verbose_name': 'Регламент скидок',
                'verbose_name_plural': 'Регламенты скидок',
            },
        ),
    ]
