# Generated by Django 4.2 on 2025-09-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_discountregulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='files',
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homeworks/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_files', to='administration.homeworksubmission')),
            ],
        ),
    ]
