# Generated by Django 4.2 on 2025-09-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_remove_homeworksubmission_files_homeworkfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='group',
            name='creation_type',
            field=models.CharField(choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], default='manual', max_length=10, verbose_name='Режим создания'),
        ),
        migrations.AddField(
            model_name='income',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата наличными'),
        ),
        migrations.AddField(
            model_name='income',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата онлайн'),
        ),
        migrations.AddField(
            model_name='income',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата переводом'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата наличными'),
        ),
        migrations.AddField(
            model_name='payment',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата онлайн'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата переводом'),
        ),
    ]
