# Generated by Django 4.2 on 2025-09-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_group_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='homework_files',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/', verbose_name='Файлы домашнего задания'),
        ),
    ]
