# Generated by Django 4.2 on 2025-09-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_group_homework_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='homework_files',
        ),
    ]
