# Generated by Django 4.2 on 2025-09-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_remove_group_homework_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='homework_files',
            field=models.FileField(blank=True, null=True, upload_to='homework'),
        ),
    ]
