# Generated by Django 4.2 on 2025-09-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_group_homework_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
