# Generated by Django 4.2 on 2025-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_delete_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000, verbose_name='Оплата наличными'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000, verbose_name='Оплата онлайн'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000, verbose_name='Оплата переводом'),
        ),
    ]
